swagger: '2.0'
info:
  version: 1.0.0
  title: Oz Users API Documentation
  description: API de lista de usuáros
paths:
  /users:
    get:
      description: Returns a list of users              
      responses:
        200:
          description: Successful response 